const DAY=86400000;
const seed={version:6,aquarium:{name:'Mijn aquarium',liters:120,startDate:'',temperature:25,type:'Zoetwater',photo:'',fish:[{id:'f1',name:'Guppy',male:0,female:0,unknown:0,since:'',note:'',photo:''},{id:'f2',name:'Platy',male:0,female:0,unknown:0,since:'',note:'',photo:''},{id:'f3',name:'Siamese algeneter (goud)',male:0,female:0,unknown:1,since:'',note:'',photo:''},{id:'f4',name:'Honinggourami',male:0,female:0,unknown:2,since:'',note:'',photo:''}],plants:[{id:'p1',name:'Riccia fluitans',count:'',since:'',note:'Drijfplant',photo:''}]},tasks:[
{id:'pad',name:'bioPad (wit)',icon:'⬜',action:'Filtervlies vervangen',interval:7,last:'2026-09-19',next:'2026-09-26',stock:4,minStock:2,replaceable:true},{id:'carb',name:'bioCarb (zwart)',icon:'⬛',action:'Koolstoffilter vervangen',interval:28,last:'2026-09-19',next:'2026-10-17',stock:1,minStock:1,replaceable:true},{id:'nitrax',name:'Nitrax (groen)',icon:'🟩',action:'Filter vervangen',interval:56,last:'2026-09-19',next:'2026-11-14',stock:1,minStock:1,replaceable:true},{id:'blue',name:'bioPlus fine (blauw)',icon:'🟦',action:'Controleren / vervangen',interval:182,last:'2026-09-19',next:'2027-03-20',stock:1,minStock:1,replaceable:true,check:true},{id:'water',name:'Water verversen',icon:'💧',action:'30% (± 36 liter)',interval:7,last:'2026-09-19',next:'2026-09-26'},{id:'clean',name:'Filter reinigen',icon:'⚙️',action:'Sponzen voorzichtig in aquariumwater uitspoelen',interval:28,last:'2026-09-19',next:'2026-10-17'}],timeline:[],history:[{date:'2026-09-19',name:'bioPad (wit)',action:'Vervangen'},{date:'2026-09-19',name:'bioCarb (zwart)',action:'Vervangen'}],water:[],settings:{notifications:false}};
let deferredInstallPrompt=null;
let activeScreen='home';
let data=JSON.parse(localStorage.getItem('aquaCare')||'null')||structuredClone(seed);
function migrate(){data.version=6;data.timeline??=[];data.settings??={notifications:false};data.aquarium.photo??='';data.aquarium.fish??=[];data.aquarium.plants??=[];data.aquarium.fish=data.aquarium.fish.map((x,i)=>{let count=Number(x.count)||0,m=x.male??0,f=x.female??0,u=x.unknown; if(u===undefined)u=count;return {...x,id:x.id||'f'+i,male:Number(m)||0,female:Number(f)||0,unknown:Number(u)||0,photo:x.photo||''}});data.aquarium.plants=data.aquarium.plants.map((x,i)=>({...x,id:x.id||'p'+i,photo:x.photo||''}));for(const t of data.tasks){if(t.stock!==undefined){t.minStock??=1;t.replaceable??=true;t.shopUrl??=''}}}migrate();
const save=()=>localStorage.setItem('aquaCare',JSON.stringify(data));save();
const localDate=()=>{let d=new Date(),off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,10)},fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('nl-BE',{day:'numeric',month:'short',year:'numeric'}),days=d=>Math.ceil((new Date(d+'T12:00:00')-new Date(localDate()+'T12:00:00'))/DAY),addDays=(date,n)=>{let d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)},esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(t){let n=days(t.next);if(n<0)return{cls:'late',label:`${-n} dag${n===-1?'':'en'} te laat`,dot:'🔴'};if(n===0)return{cls:'today',label:'vandaag',dot:'🟠'};if(n<=3)return{cls:'soon',label:`over ${n} dag${n===1?'':'en'}`,dot:'🟠'};return{cls:'ok',label:`over ${n} dagen`,dot:'🟢'}}
function taskCard(t){let s=status(t);return `<div class="card task-card"><div class="icon">${t.icon}</div><div class="grow"><div class="title">${esc(t.name)}</div><div class="meta">${esc(t.action)}</div><div class="due ${s.cls}">${s.dot} ${fmt(t.next)} · ${s.label}</div>${t.stock!==undefined?`<div class="stockline ${t.stock<=t.minStock?'low':''}">Voorraad: <b>${t.stock}</b> · minimum ${t.minStock}</div>`:''}</div><button class="done" onclick="openComplete('${t.id}')">✓ Uitgevoerd</button></div>`}
function animalCard(x,type){let img=x.photo?`<img class="photo" src="${x.photo}">`:`<div class="photo-placeholder">${type==='fish'?'🐟':'🌿'}</div>`;let extra=type==='fish'?`Totaal ${x.male+x.female+x.unknown} · ♂ ${x.male} · ♀ ${x.female} · ? ${x.unknown}`:`${x.count!==''?'Aantal '+x.count:''}`;return `<div class="card">${img}<div class="grow"><div class="title">${esc(x.name)}</div><div class="meta">${extra}${x.since?' · sinds '+fmt(x.since):''}${x.note?' · '+esc(x.note):''}</div></div><button class="mini" onclick="openAnimal('${type}','${x.id}')">✏️</button></div>`}
function render(){let stock=data.tasks.filter(t=>t.stock!==undefined),shopping=stock.filter(t=>t.stock<=t.minStock),fish=data.aquarium.fish,plants=data.aquarium.plants;document.querySelector('#app').innerHTML=`<main class="app"><section id="home" class="screen active"><div class="hero"><div class="small white">AQUA CARE · 1.2</div><h1>${esc(data.aquarium.name)}</h1><p>${data.aquarium.liters} liter · ${esc(data.aquarium.type)} · ${data.aquarium.temperature||'-'} °C</p><p>${fish.length} vissoorten · ${plants.length} plantsoorten</p>${data.aquarium.photo?`<img class="photo hero-photo" src="${data.aquarium.photo}">`:''}<div class="status ${shopping.length?'status-link':''}" ${shopping.length?'onclick="go(\'stock\')" role="button" tabindex="0"':''}>${shopping.length?'🛒 '+shopping.length+' product(en) op boodschappenlijst · bekijken →':'✓ Planning en voorraad in orde'}</div></div>${!data.settings.notifications?`<div class="notice">🔔 Wil je meldingen bij onderhoud? <button class="btn secondary" onclick="enableNotifications()">Meldingen aanzetten</button></div>`:''}${deferredInstallPrompt?`<div class="notice install">📱 Installeer Aqua Care als app op dit toestel. <button class="btn secondary" onclick="installApp()">App installeren</button></div>`:''}<div class="section"><h2>Volgend onderhoud</h2>${[...data.tasks].sort((a,b)=>a.next.localeCompare(b.next)).map(taskCard).join('')}</div></section>
<section id="tasks" class="screen"><div class="topbar"><h1>Onderhoud</h1><button class="btn" onclick="openAdd()">+ Taak</button></div><div class="section">${data.tasks.map(taskCard).join('')}</div></section>
<section id="stock" class="screen"><div class="topbar"><h1>Voorraad</h1></div><div class="section">${shopping.length?`<div class="shopping"><h2>🛒 Boodschappenlijst</h2>${shopping.map(t=>`<div class="shoprow"><span>${t.icon} ${esc(t.name)}</span><div class="row">${t.shopUrl?`<button class="btn secondary" onclick="openShop('${t.id}')">🛒 Bestellen</button>`:''}<button class="btn secondary" onclick="restock('${t.id}')">+ Aangevuld</button></div></div>`).join('')}</div>`:`<div class="allgood">✓ Niets te kopen</div>`}${stock.map(t=>`<div class="card"><div class="icon">${t.icon}</div><div class="grow"><div class="title">${esc(t.name)}</div><div class="meta">Voorraad <b>${t.stock}</b> · minimum ${t.minStock}</div><div class="shoplink-slot">${t.shopUrl?'🛒 Bestellink ingesteld':'&nbsp;'}</div></div><button class="mini" onclick="editStock('${t.id}')">✏️</button><div class="stepper"><button onclick="stockChange('${t.id}',-1)">−</button><b>${t.stock}</b><button onclick="stockChange('${t.id}',1)">+</button></div></div>`).join('')}</div></section>
<section id="log" class="screen"><div class="topbar"><h1>Logboek</h1></div><div class="section">${data.history.length?[...data.history].reverse().map(h=>`<div class="card"><div class="icon">✓</div><div><div class="title">${esc(h.name)}</div><div class="meta">${esc(h.action)} · ${fmt(h.date)}</div></div></div>`).join(''):'Nog geen historiek.'}</div></section>
<section id="aqua" class="screen"><div class="topbar"><h1>Mijn aquarium</h1><button class="btn" onclick="openProfile()">Bewerken</button></div><div class="backupbar"><button class="btn secondary" onclick="exportBackup()">⬇️ Back-up</button><button class="btn secondary" onclick="document.getElementById('backupFile').click()">⬆️ Herstellen</button><input id="backupFile" class="hidden" type="file" accept="application/json" onchange="importBackup(this)"></div><div class="section">${data.aquarium.photo?`<img class="photo hero-photo" src="${data.aquarium.photo}">`:''}<div class="profile card"><div class="icon">🐠</div><div><div class="title">${esc(data.aquarium.name)}</div><div class="meta">${data.aquarium.liters} liter · ${esc(data.aquarium.type)} · ${data.aquarium.temperature||'-'} °C</div></div></div><div class="subhead"><h2>🐟 Vissen</h2><button class="btn secondary" onclick="openAnimal('fish')">+ Vis</button></div>${fish.map(x=>animalCard(x,'fish')).join('')}<div class="subhead"><h2>🌿 Planten</h2><button class="btn secondary" onclick="openAnimal('plant')">+ Plant</button></div>${plants.map(x=>animalCard(x,'plant')).join('')}<div class="subhead"><h2>🕘 Historiek</h2><button class="btn secondary" onclick="addTimelineNote()">+ Notitie</button></div>${timelineHtml()}</div></section>
<nav class="nav"><button class="active" onclick="go('home',this)">🏠<br>Home</button><button onclick="go('tasks',this)">☑️<br>Taken</button><button onclick="go('stock',this)">📦<br>Voorraad</button><button onclick="go('log',this)">📖<br>Logboek</button><button onclick="go('aqua',this)">🐠<br>Aquarium</button></nav></main><dialog id="dlg"></dialog><dialog id="animalDlg"></dialog><dialog id="profileDlg"></dialog><dialog id="addDlg"></dialog>`;restoreScreen();}
function restoreScreen(){let screens=[...document.querySelectorAll('.screen')],buttons=[...document.querySelectorAll('.nav button')],screen=document.querySelector('#'+activeScreen);screens.forEach(x=>x.classList.remove('active'));(screen||document.querySelector('#home'))?.classList.add('active');buttons.forEach(x=>x.classList.remove('active'));let i=['home','tasks','stock','log','aqua'].indexOf(activeScreen);if(i<0)i=0;buttons[i]?.classList.add('active')}
window.go=(id,b)=>{activeScreen=id;restoreScreen()};
window.openComplete=id=>{let t=data.tasks.find(x=>x.id===id),actions=t.replaceable?['Vervangen','Gereinigd','Gecontroleerd']:t.id==='water'?['Water ververst']:['Uitgevoerd','Gereinigd'];dlg.innerHTML=`<h2>${t.icon} ${esc(t.name)}</h2><p>Wat heb je gedaan?</p><div class="actiongrid">${actions.map(a=>`<button class="actionbtn" onclick="completeTask('${id}','${a}')">✓<span>${a}</span></button>`).join('')}</div><button class="btn secondary full" onclick="dlg.close()">Annuleren</button>`;dlg.showModal()};
window.completeTask=(id,action)=>{let t=data.tasks.find(x=>x.id===id),today=localDate();data.history.push({date:today,name:t.name,action});if(action==='Vervangen'&&t.stock!==undefined)t.stock=Math.max(0,t.stock-1);if(action==='Vervangen'||action==='Water ververst'||action==='Uitgevoerd'||(t.check&&action==='Gecontroleerd')){t.last=today;t.next=addDays(today,t.interval)}save();dlg.close();render();checkNotifications()};
window.openShop=id=>{let t=data.tasks.find(x=>x.id===id);if(t?.shopUrl){let u=t.shopUrl.trim();if(!/^https?:\/\//i.test(u))u='https://'+u;window.open(u,'_blank','noopener')}};
window.editStock=id=>{let t=data.tasks.find(x=>x.id===id);let u=prompt('Bestellink voor '+t.name,t.shopUrl||'');if(u!==null){t.shopUrl=u.trim();save();render()}};
window.stockChange=(id,n)=>{let t=data.tasks.find(x=>x.id===id);t.stock=Math.max(0,t.stock+n);save();render()};window.restock=id=>{let n=Number(prompt('Hoeveel stuks heb je gekocht?','2'));if(n>0){let t=data.tasks.find(x=>x.id===id);t.stock+=n;data.history.push({date:localDate(),name:t.name,action:`Voorraad +${n}`});save();render()}};
function addTimeline(type,title,detail='',photo=''){data.timeline.push({id:'h'+Date.now()+Math.random(),date:localDate(),type,title,detail,photo})}
function timelineHtml(){if(!data.timeline.length)return '<div class="empty">Nog geen gebeurtenissen. Wijzigingen aan vissen en planten worden vanaf nu automatisch bijgehouden.</div>';return [...data.timeline].reverse().slice(0,30).map(h=>`<div class="timeline"><div class="timeline-dot">${h.type==='fish'?'🐟':h.type==='plant'?'🌿':h.type==='photo'?'📷':'📝'}</div><div class="grow"><div class="title">${esc(h.title)}</div><div class="meta">${fmt(h.date)}${h.detail?' · '+esc(h.detail):''}</div>${h.photo?`<img class="timeline-photo" src="${h.photo}" alt="Aquariumfoto" onclick="openHistoryPhoto(this.src)">`:''}</div></div>`).join('')}
window.openHistoryPhoto=src=>{let d=document.createElement('dialog');d.className='photo-dialog';d.innerHTML=`<img src="${src}" alt="Aquariumfoto"><button class="btn secondary full" onclick="this.closest('dialog').close();this.closest('dialog').remove()">Sluiten</button>`;document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d){d.close();d.remove()}});d.showModal()};
window.addTimelineNote=()=>{let n=prompt('Wat wil je aan de aquariumhistoriek toevoegen?');if(n?.trim()){addTimeline('note','Notitie',n.trim());save();render()}};
function readPhoto(input,cb){let f=input.files?.[0];if(!f)return cb('');if(f.size>8*1024*1024)return alert('Kies een foto kleiner dan 8 MB.');let img=new Image(),r=new FileReader();r.onload=e=>{img.onload=()=>{let max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);cb(c.toDataURL('image/jpeg',.78))};img.src=e.target.result};r.readAsDataURL(f)}
window.openAnimal=(type,id='')=>{let list=type==='fish'?data.aquarium.fish:data.aquarium.plants,x=id?list.find(v=>v.id===id):null;animalDlg.innerHTML=`<h2>${type==='fish'?'🐟 Vis':'🌿 Plant'} ${x?'bewerken':'toevoegen'}</h2>${x?.photo?`<img class="photo-preview" src="${x.photo}">`:''}<label>Foto</label><input id="anPhoto" type="file" accept="image/*"><label>Soort / naam</label><div class="species-name-row"><input id="anName" value="${esc(x?.name||'')}"><button type="button" class="btn secondary" onclick="searchSpecies('${type}')">🔍 Zoeken</button></div><div id="speciesResults"></div>${type==='fish'?`<div class="counts"><div><label>♂ Mannetjes</label><input id="anMale" type="number" min="0" value="${x?.male??0}"></div><div><label>♀ Vrouwtjes</label><input id="anFemale" type="number" min="0" value="${x?.female??0}"></div><div><label>? Jong/onbekend</label><input id="anUnknown" type="number" min="0" value="${x?.unknown??0}"></div></div>`:`<label>Aantal</label><input id="anCount" type="number" min="0" value="${x?.count??''}">`}<label>Toegevoegd sinds</label><input id="anSince" type="date" value="${x?.since||''}"><label>Notitie</label><input id="anNote" value="${esc(x?.note||'')}"><br><br><div class="row"><button class="btn" onclick="saveAnimal('${type}','${id}')">Bewaren</button>${x?`<button class="btn danger" onclick="deleteAnimal('${type}','${id}')">Verwijderen</button>`:''}<button class="btn secondary" onclick="animalDlg.close()">Annuleren</button></div>`;animalDlg.showModal()};
window.searchSpecies=async type=>{let q=anName.value.trim();if(!q){q=prompt('Geef een deel van de naam of een beschrijving in, bv. Anubias, javavaren of guppy.','');if(!q?.trim())return;anName.value=q.trim()}let box=document.getElementById('speciesResults');box.innerHTML='<div class="species-loading">Zoeken…</div>';try{let url='https://api.inaturalist.org/v1/taxa/autocomplete?q='+encodeURIComponent(q)+'&per_page=8';let res=await fetch(url);if(!res.ok)throw new Error();let json=await res.json(),items=(json.results||[]).filter(x=>type==='fish'?['Actinopterygii','Chondrichthyes','Petromyzonti'].includes(x.iconic_taxon_name):['Plantae'].includes(x.iconic_taxon_name)).slice(0,6);if(!items.length)items=(json.results||[]).slice(0,6);box.innerHTML=items.length?items.map(x=>{let common=x.preferred_common_name||x.english_common_name||'',label=common||x.name,sub=common&&common!==x.name?x.name:'',photo=x.default_photo?.square_url||'';let payload=encodeURIComponent(JSON.stringify({label,scientific:x.name,photo}));return `<button type="button" class="species-result" data-species="${payload}" onclick="chooseSpeciesResult(this)">${photo?`<img src="${photo}" alt="">`:'<span class="species-placeholder">🔎</span>'}<span><b>${esc(label)}</b>${sub?`<small>${esc(sub)}</small>`:''}</span></button>`}).join(''):'<div class="species-loading">Geen passende soorten gevonden. Probeer een andere naam.</div>'}catch{box.innerHTML='<div class="species-loading">Zoeken lukt momenteel niet. Je kunt de naam wel handmatig invullen.</div>'}};
window.chooseSpeciesResult=el=>{try{let x=JSON.parse(decodeURIComponent(el.dataset.species));anName.value=x.label;let box=document.getElementById('speciesResults');box.innerHTML=`<div class="species-chosen">✓ ${esc(x.label)}${x.scientific&&x.scientific!==x.label?' · '+esc(x.scientific):''}</div>`}catch{alert('Deze soort kon niet geselecteerd worden.')}};
window.saveAnimal=(type,id)=>{let list=type==='fish'?data.aquarium.fish:data.aquarium.plants,x=id?list.find(v=>v.id===id):null,name=anName.value.trim();if(!name)return;let finish=photo=>{let obj={...(x||{}),id:id||type[0]+Date.now(),name,since:anSince.value,note:anNote.value.trim(),photo:photo||x?.photo||''};if(type==='fish'){obj.male=Math.max(0,+anMale.value||0);obj.female=Math.max(0,+anFemale.value||0);obj.unknown=Math.max(0,+anUnknown.value||0)}else obj.count=anCount.value===''?'':Math.max(0,+anCount.value);if(x){if(type==='fish'){let before=x.male+x.female+x.unknown,after=obj.male+obj.female+obj.unknown;if(before!==after||x.male!==obj.male||x.female!==obj.female||x.unknown!==obj.unknown)addTimeline('fish',obj.name,`Aantal gewijzigd: ${before} → ${after} · ♂ ${x.male}→${obj.male} · ♀ ${x.female}→${obj.female} · ? ${x.unknown}→${obj.unknown}`)}else if(String(x.count)!==String(obj.count))addTimeline('plant',obj.name,`Aantal gewijzigd: ${x.count||0} → ${obj.count||0}`);Object.assign(x,obj)}else{list.push(obj);addTimeline(type,obj.name,'Toegevoegd aan aquarium')}save();animalDlg.close();render();go('aqua',document.querySelectorAll('.nav button')[4])};if(anPhoto.files?.[0])readPhoto(anPhoto,finish);else finish('')};
window.deleteAnimal=(type,id)=>{if(!confirm('Verwijderen?'))return;let list=type==='fish'?data.aquarium.fish:data.aquarium.plants,x=list.find(v=>v.id===id);if(x)addTimeline(type,x.name,'Verwijderd uit aquarium');if(type==='fish')data.aquarium.fish=data.aquarium.fish.filter(x=>x.id!==id);else data.aquarium.plants=data.aquarium.plants.filter(x=>x.id!==id);save();animalDlg.close();render()};
window.openProfile=()=>{let a=data.aquarium;profileDlg.innerHTML=`<h2>🐠 Aquarium bewerken</h2>${a.photo?`<img class="photo-preview" src="${a.photo}">`:''}<label>Foto aquarium</label><input id="aqPhoto" type="file" accept="image/*"><label>Naam</label><input id="aqName" value="${esc(a.name)}"><label>Inhoud (liter)</label><input id="aqLiters" type="number" value="${a.liters}"><label>Type</label><select id="aqType"><option>Zoetwater</option><option>Zoutwater</option><option>Brakwater</option></select><label>Temperatuur °C</label><input id="aqTemp" type="number" step=".1" value="${a.temperature||''}"><label>Startdatum</label><input id="aqStart" type="date" value="${a.startDate||''}"><br><br><div class="row"><button class="btn" onclick="saveProfile()">Bewaren</button><button class="btn secondary" onclick="profileDlg.close()">Annuleren</button></div>`;profileDlg.showModal();aqType.value=a.type};
window.saveProfile=()=>{let finish=photo=>{data.aquarium.name=aqName.value.trim()||'Mijn aquarium';data.aquarium.liters=Math.max(1,+aqLiters.value||1);data.aquarium.type=aqType.value;data.aquarium.temperature=aqTemp.value?+aqTemp.value:'';data.aquarium.startDate=aqStart.value;if(photo){data.aquarium.photo=photo;addTimeline('photo','Nieuwe aquariumfoto','',photo)}save();profileDlg.close();render()};if(aqPhoto.files?.[0])readPhoto(aqPhoto,finish);else finish('')};
window.openAdd=()=>{addDlg.innerHTML=`<h2>Nieuwe taak</h2><label>Naam</label><input id="newName"><label>Interval in dagen</label><input id="newInterval" type="number" value="7"><br><br><button class="btn" onclick="addTask()">Toevoegen</button> <button class="btn secondary" onclick="addDlg.close()">Annuleren</button>`;addDlg.showModal()};window.addTask=()=>{let n=newName.value.trim(),i=+newInterval.value;if(!n||i<1)return;let today=localDate();data.tasks.push({id:'t'+Date.now(),name:n,icon:'🔧',action:'Onderhoud',interval:i,last:today,next:addDays(today,i)});save();addDlg.close();render()};
window.enableNotifications=async()=>{if(!('Notification'in window))return alert('Deze browser ondersteunt geen meldingen.');let p=await Notification.requestPermission();data.settings.notifications=p==='granted';save();render();if(p==='granted'){new Notification('Aqua Care',{body:'Meldingen zijn ingeschakeld.'});checkNotifications()}};
function checkNotifications(){if(!data.settings.notifications||Notification.permission!=='granted')return;let due=data.tasks.filter(t=>days(t.next)<=0);if(due.length)new Notification('Aqua Care · onderhoud',{body:due.map(t=>t.name).join(', ')+' vraagt aandacht.'})}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;render()});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;render()});
window.installApp=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;render()};
window.exportBackup=()=>{let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='aqua-care-backup-'+localDate()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
window.importBackup=input=>{let f=input.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let imported=JSON.parse(r.result);if(!imported.aquarium||!Array.isArray(imported.tasks))throw new Error();if(confirm('Deze back-up herstellen? De huidige lokale gegevens worden vervangen.')){data=imported;migrate();save();render();alert('Back-up hersteld.')}}catch{alert('Dit lijkt geen geldige Aqua Care back-up.')}input.value=''};r.readAsText(f)};
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});render();setTimeout(checkNotifications,800);
